title: Canal DevOps
subtitle: Resolvendo problemas do mundo real

description: 
  Canal DevOps é um blog que tem como objetivo difundir o conhecimento, técnicas e boas práticas no desenvolvimento, entrega e evolução de software. Focando em problemas do mundo real.


logo_file: logo.png  # your profile image 

# Author details
collections:
  authors:
    output: true
  levels:
    output: true

# social links 
social_username: canaldevops

toggles:
  show_author_image: false